shell/root-core.sh
shell/fzf.sh
shell/docker-ce.sh
shell/gnome-desktop/root-gnome.sh
shell/ibus-mozc.sh
shell/gnome-desktop/font.sh
shell/gnome-desktop/theme.sh
shell/gnome-desktop/icon.sh
shell/gnome-desktop/libinput-gestures.sh
shell/vlc.sh
shell/wine.sh
shell/chrome.sh
shell/apt/common.sh
shell/anyenv.sh
shell/direnv.sh
shell/yarn.sh
shell/jq.sh
shell/hcat.sh
shell/highway.sh
shell/bat.sh
shell/exa.sh
shell/ripgrep.sh
shell/xpanes.sh
shell/trans.sh
shell/certbot.sh
shell/nginx.sh
shell/apt/development.sh
shell/ctags.sh
shell/phpcs.sh
shell/eslint.sh
shell/git_find_big.sh
shell/hadolint.sh
shell/js-beautify.sh
shell/sql-formatter.sh
shell/rsense.sh
shell/ngrok.sh
shell/jmeter.sh
shell/postman.sh
shell/awscli.sh
shell/gcloud.sh
shell/font.sh
